/* ===================================================================
   Dados do Mapa Bíblico Kids — conteúdo original, linguagem infantil.
=================================================================== */

const SECTIONS = {
  pentateuco:        { label: "Pentateuco",          accent: "#7E57C2", bg: "#EDE7F6", ground: "#D8CCF0" },
  historicos_at:      { label: "Históricos",          accent: "#F0A93A", bg: "#FFF3E0", ground: "#FFDDA8" },
  poeticos:           { label: "Poéticos",            accent: "#EF476F", bg: "#FFE3EC", ground: "#FFC2D6" },
  profeticos_maiores: { label: "Proféticos Maiores",  accent: "#118AB2", bg: "#E1F5FE", ground: "#B3E5FC" },
  profeticos_menores: { label: "Proféticos Menores",  accent: "#06D6A0", bg: "#E3FBF4", ground: "#BDF3E1" },
  evangelhos:         { label: "Evangelhos",          accent: "#FFC93C", bg: "#FFF9E1", ground: "#FFE9A8" },
  historicos_nt:      { label: "Histórico (Atos)",    accent: "#F0A93A", bg: "#FFF3E0", ground: "#FFDDA8" },
  cartas_paulinas:    { label: "Cartas de Paulo",     accent: "#7CB342", bg: "#F1F8E9", ground: "#DCEDC8" },
  cartas_gerais:      { label: "Cartas Gerais",       accent: "#7B61FF", bg: "#EEEBFF", ground: "#D9D2FF" },
  apocalipse:         { label: "Apocalipse",          accent: "#118AB2", bg: "#E1F0FF", ground: "#BFDCFF" },
};

const BIBLE_BOOKS = [
  // ---------------- PENTATEUCO ----------------
  { n:1, id:"genesis", test:"AT", section:"pentateuco", name:"Gênesis",
    icons:["sun","tree","ark"],
    sabia:"Gênesis é o primeiro livro da Bíblia. Ele conta como Deus criou o mundo, os animais e as primeiras pessoas, e depois fala sobre famílias que confiaram em Deus, como Noé e sua arca.",
    tema:"Deus criou tudo com amor, e Ele tem um plano bom para cada pessoa.",
    activity:{ type:"count", icon:"star", color:"#FFD54F", count:7, question:"Deus criou o mundo em 7 dias! Encontre as 7 estrelinhas escondidas." },
    extra:{ icons:["ark","water"], activity:{ type:"sequence", prompt:"Numere a história de Noé na ordem certa!",
      events:["Deus pede para Noé construir uma arca","Os animais entram na arca, dois a dois","Chove por muitos dias","A arca descansa e uma pomba traz um ramo de oliveira"] } } },

  { n:2, id:"exodo", test:"AT", section:"pentateuco", name:"Êxodo",
    icons:["water","person"],
    sabia:"Êxodo conta como Deus escolheu Moisés para tirar o povo de Israel da escravidão no Egito. Deus abriu um caminho no meio do mar para o povo passar em segurança!",
    tema:"Deus liberta e cuida do seu povo, mesmo quando o caminho parece impossível.",
    activity:{ type:"maze", prompt:"Ajude Moisés a encontrar o caminho até a terra prometida!", startIcon:"person", endIcon:"star" },
    extra:{ icons:["tablets"], activity:{ type:"fill", prompt:"Complete com a palavra certa!",
      sentence:"Deus deu a Moisés os ____ Mandamentos no monte Sinai.", wordBank:["Dez","Cinco","Vinte"] } } },

  { n:3, id:"levitico", test:"AT", section:"pentateuco", name:"Levítico",
    icons:["altar","candle"],
    sabia:"Levítico ensina como o povo de Deus deveria adorar e viver de um jeito especial, com a ajuda dos sacerdotes que cuidavam das oferendas.",
    tema:"Deus quer que a gente viva de um jeito bom, cuidando do que é certo.",
    activity:{ type:"truefalse", statements:["Levítico fala sobre como o povo deveria adorar a Deus.","Os sacerdotes ajudavam o povo nas oferendas.","Levítico é o último livro da Bíblia."] } },

  { n:4, id:"numeros", test:"AT", section:"pentateuco", name:"Números",
    icons:["tent","road"],
    sabia:"Números conta a longa viagem do povo de Israel pelo deserto, contando quantas pessoas havia em cada tribo, a caminho da terra prometida.",
    tema:"Mesmo numa jornada longa, Deus continua guiando o seu povo, passo a passo.",
    activity:{ type:"count", icon:"tent", color:"#D9A566", count:6, question:"Quantas tendas você encontra no acampamento do povo?" } },

  { n:5, id:"deuteronomio", test:"AT", section:"pentateuco", name:"Deuteronômio",
    icons:["mountain","scroll"],
    sabia:"Deuteronômio é o último livro sobre Moisés. Nele, ele relembra o povo sobre as leis de Deus antes de entrarem na terra prometida.",
    tema:"É importante guardar no coração os ensinamentos de Deus.",
    activity:{ type:"fill", sentence:"Antes de morrer, ____ relembrou o povo sobre as leis de Deus.", wordBank:["Moisés","Josué","Davi"] } },

  // ---------------- HISTÓRICOS (AT) ----------------
  { n:6, id:"josue", test:"AT", section:"historicos_at", name:"Josué",
    icons:["wall","trumpet"],
    sabia:"Josué se tornou o novo líder do povo depois de Moisés. Deus ajudou Josué a conquistar a cidade de Jericó: as muralhas caíram depois que o povo tocou trombetas e gritou!",
    tema:"Quando confiamos e obedecemos a Deus, coisas incríveis podem acontecer.",
    activity:{ type:"count", icon:"trumpet", color:"#FFD166", count:7, question:"Quantas trombetas você consegue encontrar ao redor da muralha?" } },

  { n:7, id:"juizes", test:"AT", section:"historicos_at", name:"Juízes",
    icons:["shield","person"],
    sabia:"Juízes conta a história de vários heróis corajosos que Deus escolheu para ajudar e proteger o povo de Israel em tempos difíceis.",
    tema:"Deus levanta pessoas corajosas para ajudar quem precisa.",
    activity:{ type:"match", prompt:"Ligue cada juiz(a) à sua história!", left:["Gideão","Sansão","Débora"], right:["Venceu com poucos soldados","Lutou com muita força","Foi uma juíza sábia"] } },

  { n:8, id:"rute", test:"AT", section:"historicos_at", name:"Rute",
    icons:["wheat","person"],
    sabia:"Rute foi uma mulher muito boa e leal, que cuidou de sua sogra Noemi com carinho, mesmo em tempos difíceis.",
    tema:"A bondade e a amizade fazem toda a diferença na vida das pessoas.",
    activity:{ type:"quiz", prompt:"Circule a resposta certa!", question:"Qual atitude mostra bondade, como a de Rute?", options:["Ajudar alguém que está precisando","Ficar bravo sem motivo","Não compartilhar os brinquedos"] } },

  { n:9, id:"1samuel", test:"AT", section:"historicos_at", name:"1 Samuel",
    icons:["shield","crown"],
    sabia:"1 Samuel conta sobre o profeta Samuel, o primeiro rei Saul, e sobre um jovem corajoso chamado Davi, que venceu o gigante Golias confiando em Deus.",
    tema:"Com a força de Deus, até um pequeno pode vencer um grande desafio.",
    activity:{ type:"sequence", prompt:"Numere a história de Davi e Golias!", events:["Davi leva comida para os irmãos no exército","Davi enfrenta Golias com uma pedra e um estilingue","Golias cai e o exército comemora","Davi se torna conhecido como um herói"] } },

  { n:10, id:"2samuel", test:"AT", section:"historicos_at", name:"2 Samuel",
    icons:["crown","harp"],
    sabia:"2 Samuel mostra Davi se tornando rei de Israel. Ele amava a Deus e escrevia canções, mesmo cometendo alguns erros ao longo da vida.",
    tema:"Mesmo quando erramos, podemos pedir perdão e continuar confiando em Deus.",
    activity:{ type:"truefalse", statements:["Davi se tornou rei de Israel.","Davi nunca cometeu nenhum erro.","Davi amava adorar a Deus."] } },

  { n:11, id:"1reis", test:"AT", section:"historicos_at", name:"1 Reis",
    icons:["crown","altar"],
    sabia:"1 Reis conta sobre o rei Salomão, que pediu sabedoria a Deus e construiu um lindo templo. Depois, o reino se dividiu em duas partes.",
    tema:"Pedir sabedoria a Deus é uma escolha muito inteligente.",
    activity:{ type:"quiz", question:"O que o rei Salomão pediu a Deus?", options:["Sabedoria para governar bem","Muitos brinquedos","Um castelo maior"] } },

  { n:12, id:"2reis", test:"AT", section:"historicos_at", name:"2 Reis",
    icons:["altar","scroll"],
    sabia:"2 Reis fala sobre reis bons e maus, e sobre profetas corajosos como Elias e Eliseu, que anunciavam a palavra de Deus.",
    tema:"Ouvir os avisos de Deus ajuda a gente a fazer escolhas melhores.",
    activity:{ type:"match", left:["Elias","Eliseu"], right:["Subiu ao céu num redemoinho","Recebeu o manto de Elias"] } },

  { n:13, id:"1cronicas", test:"AT", section:"historicos_at", name:"1 Crônicas",
    icons:["crown","scroll"],
    sabia:"1 Crônicas relembra a história do povo de Israel, desde as primeiras famílias até o reinado do rei Davi.",
    tema:"Nossa história e nossa família são importantes para Deus.",
    activity:{ type:"draw", prompt:"Desenhe a sua família! Assim como o povo de Israel, a sua família também é especial para Deus." } },

  { n:14, id:"2cronicas", test:"AT", section:"historicos_at", name:"2 Crônicas",
    icons:["altar","cityWall"],
    sabia:"2 Crônicas conta sobre os reis de Judá e a construção do templo, mostrando o cuidado de Deus mesmo quando o povo se afastava Dele.",
    tema:"Deus está sempre pronto a perdoar quem volta para Ele.",
    activity:{ type:"truefalse", statements:["O templo era um lugar para adorar a Deus.","Os reis sempre obedeciam a Deus.","Deus perdoa quem se arrepende."] } },

  { n:15, id:"esdras", test:"AT", section:"historicos_at", name:"Esdras",
    icons:["cityWall","scroll"],
    sabia:"Esdras conta como o povo de Israel voltou para casa depois de muito tempo longe, e reconstruiu o templo para adorar a Deus outra vez.",
    tema:"É bom voltar e recomeçar quando algo importante foi perdido.",
    activity:{ type:"fill", sentence:"O povo voltou para reconstruir o ____ de Deus.", wordBank:["templo","barco","muro"] } },

  { n:16, id:"neemias", test:"AT", section:"historicos_at", name:"Neemias",
    icons:["wall","person"],
    sabia:"Neemias ficou triste ao saber que os muros de Jerusalém estavam destruídos, e ajudou o povo a reconstruí-los trabalhando em equipe.",
    tema:"Trabalhar em equipe ajuda a superar grandes desafios.",
    activity:{ type:"maze", prompt:"Ajude os construtores a chegarem até o muro!", startIcon:"person", endIcon:"wall" } },

  { n:17, id:"ester", test:"AT", section:"historicos_at", name:"Ester",
    icons:["crown","scroll"],
    sabia:"Ester era uma jovem corajosa que se tornou rainha e ajudou a salvar o seu povo de um grande perigo, confiando em Deus mesmo com medo.",
    tema:"Deus pode nos usar para fazer coisas corajosas, no momento certo.",
    activity:{ type:"quiz", question:"O que Ester fez para ajudar o seu povo?", options:["Foi corajosa e falou com o rei","Escondeu-se e não fez nada","Foi embora do reino"] } },

  // ---------------- POÉTICOS ----------------
  { n:18, id:"jo", test:"AT", section:"poeticos", name:"Jó",
    icons:["sheep","star"],
    sabia:"Jó era um homem bom que passou por momentos muito difíceis, mas continuou confiando em Deus. No final, Deus abençoou sua vida outra vez.",
    tema:"Mesmo nos dias difíceis, podemos continuar confiando em Deus.",
    activity:{ type:"truefalse", statements:["Jó continuou confiando em Deus mesmo triste.","Deus esqueceu de Jó para sempre."] } },

  { n:19, id:"salmos", test:"AT", section:"poeticos", name:"Salmos",
    icons:["harp","music"],
    sabia:"Salmos é um livro cheio de músicas e orações para louvar e conversar com Deus, muitas escritas pelo rei Davi.",
    tema:"Podemos falar com Deus sobre tudo o que sentimos: alegria, medo ou gratidão.",
    activity:{ type:"draw", prompt:"Desenhe algo pelo qual você quer agradecer a Deus!" },
    extra:{ icons:["star","music"], activity:{ type:"fill", sentence:"Salmos é um livro cheio de ____ e orações.", wordBank:["músicas","mapas","receitas"] } } },

  { n:20, id:"proverbios", test:"AT", section:"poeticos", name:"Provérbios",
    icons:["scroll","balance"],
    sabia:"Provérbios é um livro cheio de conselhos sábios, escritos principalmente pelo rei Salomão, para nos ajudar a fazer escolhas melhores.",
    tema:"A sabedoria nos ajuda a escolher o caminho certo.",
    activity:{ type:"quiz", prompt:"Circule a atitude mais sábia!", question:"Qual dessas atitudes mostra sabedoria?", options:["Pensar antes de agir e ouvir bons conselhos","Fazer tudo com raiva e pressa","Não escutar ninguém"] } },

  { n:21, id:"eclesiastes", test:"AT", section:"poeticos", name:"Eclesiastes",
    icons:["sun","scroll"],
    sabia:"Eclesiastes fala sobre buscar o que realmente importa na vida, e mostra que viver perto de Deus é o mais valioso de tudo.",
    tema:"As coisas mais importantes da vida não são brinquedos ou riquezas, mas o amor de Deus.",
    activity:{ type:"circle", question:"O que é mais importante de verdade?", options:["Amar a Deus e as pessoas","Ter muitos brinquedos","Ser o mais rápido de todos"] } },

  { n:22, id:"canticos", test:"AT", section:"poeticos", name:"Cânticos",
    icons:["heart","vine"],
    sabia:"Cânticos é um livro poético que fala sobre o amor, usando palavras bonitas, como uma canção.",
    tema:"O amor é um presente lindo que Deus criou.",
    activity:{ type:"draw", prompt:"Desenhe um coração e escreva o nome de alguém que você ama muito!" } },

  // ---------------- PROFÉTICOS MAIORES ----------------
  { n:23, id:"isaias", test:"AT", section:"profeticos_maiores", name:"Isaías",
    icons:["star","scroll"],
    sabia:"Isaías foi um profeta que anunciou, muito tempo antes, que Deus enviaria um Salvador para o mundo.",
    tema:"Deus sempre cumpre as suas promessas, mesmo que demore.",
    activity:{ type:"wordsearch", prompt:"Encontre as palavras escondidas!", words:["ISAIAS","PROFETA","PROMESSA","ESPERANCA"] },
    extra:{ icons:["star"], activity:{ type:"fill", sentence:"Isaías anunciou que Deus enviaria um ____.", wordBank:["Salvador","Dragão","Tesouro"] } } },

  { n:24, id:"jeremias", test:"AT", section:"profeticos_maiores", name:"Jeremias",
    icons:["scroll","cloud"],
    sabia:"Jeremias foi um profeta que, mesmo triste, avisou o povo com muita coragem para que voltassem a confiar em Deus.",
    tema:"Um bom amigo nos avisa, mesmo quando a verdade é difícil de ouvir.",
    activity:{ type:"truefalse", statements:["Jeremias avisava o povo com coragem.","Jeremias não se importava com o povo."] } },

  { n:25, id:"lamentacoes", test:"AT", section:"profeticos_maiores", name:"Lamentações",
    icons:["cloud","cityWall"],
    sabia:"Lamentações é uma oração triste sobre a queda da cidade de Jerusalém, mas que também lembra que o amor de Deus nunca acaba.",
    tema:"Mesmo triste, podemos lembrar que o cuidado de Deus continua todos os dias.",
    activity:{ type:"fill", sentence:"O amor de Deus é ____ todos os dias.", wordBank:["novo","pequeno","triste"] } },

  { n:26, id:"ezequiel", test:"AT", section:"profeticos_maiores", name:"Ezequiel",
    icons:["dove","tree"],
    sabia:"Ezequiel teve visões especiais de Deus e anunciou que Deus podia trazer vida nova mesmo onde parecia não haver esperança.",
    tema:"Deus pode transformar tristeza em esperança.",
    activity:{ type:"draw", prompt:"Desenhe algo que representa uma esperança nova!" } },

  { n:27, id:"daniel", test:"AT", section:"profeticos_maiores", name:"Daniel",
    icons:["lion","crown"],
    sabia:"Daniel confiava tanto em Deus que, mesmo jogado numa cova de leões, Deus o protegeu e nada aconteceu com ele!",
    tema:"Deus cuida de quem confia Nele, mesmo em situações assustadoras.",
    activity:{ type:"count", icon:"lion", color:"#F0A93A", count:5, question:"Quantos leões você encontra na cova de Daniel?" } },

  // ---------------- PROFÉTICOS MENORES ----------------
  { n:28, id:"oseias", test:"AT", section:"profeticos_menores", name:"Oseias",
    icons:["heart","sheep"],
    sabia:"Oseias mostra o quanto Deus ama o seu povo, com um amor fiel que nunca desiste, mesmo quando as pessoas se afastam.",
    tema:"O amor de Deus por nós nunca acaba.",
    activity:{ type:"truefalse", statements:["O amor de Deus por nós nunca acaba.","Deus desiste fácil das pessoas."] } },

  { n:29, id:"joel", test:"AT", section:"profeticos_menores", name:"Joel",
    icons:["sun","wheat"],
    sabia:"Joel fala sobre um tempo difícil para o povo, mas também sobre a promessa de Deus de renovar e abençoar tudo outra vez.",
    tema:"Depois das dificuldades, Deus pode trazer coisas novas e boas.",
    activity:{ type:"fill", sentence:"Depois da tempestade, Deus promete trazer coisas ____.", wordBank:["novas e boas","assustadoras","tristes"] } },

  { n:30, id:"amos", test:"AT", section:"profeticos_menores", name:"Amós",
    icons:["balance","sheep"],
    sabia:"Amós era um pastor de ovelhas que Deus escolheu para pedir que o povo tratasse todos com justiça e bondade, especialmente quem precisa de ajuda.",
    tema:"Deus quer que sejamos justos e gentis com todas as pessoas.",
    activity:{ type:"quiz", question:"O que Amós pediu que o povo fizesse?", options:["Tratar todos com justiça e cuidado","Ignorar quem precisa de ajuda","Guardar tudo só para si"] } },

  { n:31, id:"obadias", test:"AT", section:"profeticos_menores", name:"Obadias",
    icons:["mountain","crown"],
    sabia:"Obadias é um livro bem curtinho. Ele ensina que Deus não gosta quando as pessoas ficam orgulhosas demais e tratam os outros mal.",
    tema:"É bom ser humilde e gentil, sem se achar melhor que ninguém.",
    activity:{ type:"quiz", question:"Qual atitude agrada a Deus, segundo Obadias?", options:["Ser humilde e gentil","Se achar melhor que todos","Zombar dos outros"] } },

  { n:32, id:"jonas", test:"AT", section:"profeticos_menores", name:"Jonas",
    icons:["bigFish","boat"],
    sabia:"Jonas tentou fugir da missão que Deus tinha dado a ele, mas Deus cuidou dele mesmo dentro de um grande peixe, e Jonas aprendeu a obedecer.",
    tema:"É melhor obedecer a Deus logo, em vez de fugir.",
    activity:{ type:"maze", prompt:"Ajude Jonas a encontrar o caminho até Nínive!", startIcon:"boat", endIcon:"cityWall" } },

  { n:33, id:"miqueias", test:"AT", section:"profeticos_menores", name:"Miqueias",
    icons:["balance","star"],
    sabia:"Miqueias pediu que o povo agisse com justiça, amasse a bondade e vivesse humildemente com Deus. Ele também anunciou onde o Salvador iria nascer: Belém!",
    tema:"Deus quer justiça, bondade e humildade em nós.",
    activity:{ type:"fill", sentence:"Miqueias anunciou que o Salvador nasceria em ____.", wordBank:["Belém","Roma","Jericó"] } },

  { n:34, id:"naum", test:"AT", section:"profeticos_menores", name:"Naum",
    icons:["cityWall","mountain"],
    sabia:"Naum é outro livro curtinho da Bíblia. Ele fala que Deus é justo e cuida de quem sofre injustiça.",
    tema:"Deus vê tudo e faz justiça no tempo certo.",
    activity:{ type:"truefalse", statements:["Deus se importa com quem sofre.","Deus não vê o que acontece."] } },

  { n:35, id:"habacuque", test:"AT", section:"profeticos_menores", name:"Habacuque",
    icons:["cloud","star"],
    sabia:"Habacuque fez perguntas sinceras a Deus quando não entendia as coisas, e aprendeu a confiar mesmo sem todas as respostas.",
    tema:"Podemos confiar em Deus mesmo quando não entendemos tudo.",
    activity:{ type:"draw", prompt:"Desenhe algo em que você confia, mesmo sem entender tudo sobre isso!" } },

  { n:36, id:"sofonias", test:"AT", section:"profeticos_menores", name:"Sofonias",
    icons:["sun","dove"],
    sabia:"Sofonias avisou o povo para mudar de atitude, e prometeu que Deus se alegra com quem é do seu povo.",
    tema:"Deus se alegra conosco, como alguém que canta de alegria por nós.",
    activity:{ type:"truefalse", statements:["Deus se alegra com o seu povo.","Deus fica bravo o tempo todo."] } },

  { n:37, id:"ageu", test:"AT", section:"profeticos_menores", name:"Ageu",
    icons:["cityWall","altar"],
    sabia:"Ageu incentivou o povo a terminar de reconstruir o templo de Deus, colocando as coisas importantes em primeiro lugar.",
    tema:"É importante colocar Deus em primeiro lugar em nossa vida.",
    activity:{ type:"quiz", question:"O que Ageu pediu que o povo fizesse primeiro?", options:["Terminar a casa de Deus","Construir suas próprias casas primeiro","Esquecer o templo"] } },

  { n:38, id:"zacarias", test:"AT", section:"profeticos_menores", name:"Zacarias",
    icons:["star","crown"],
    sabia:"Zacarias teve visões cheias de esperança e anunciou que um rei viria de um jeito humilde, montado em um jumentinho.",
    tema:"Deus cumpre suas promessas, mesmo de formas surpreendentes.",
    activity:{ type:"fill", sentence:"O rei prometido chegaria montado em um ____.", wordBank:["jumentinho","cavalo grande","carro"] } },

  { n:39, id:"malaquias", test:"AT", section:"profeticos_menores", name:"Malaquias",
    icons:["heart","altar"],
    sabia:"Malaquias é o último livro do Antigo Testamento. Ele lembra o povo do grande amor de Deus e pede fidelidade e respeito a Ele.",
    tema:"Deus merece todo o nosso amor e respeito.",
    activity:{ type:"truefalse", statements:["Malaquias é o último livro do Antigo Testamento.","Deus não se importa se somos fiéis."] } },

  // ---------------- EVANGELHOS ----------------
  { n:40, id:"mateus", test:"NT", section:"evangelhos", name:"Mateus",
    icons:["manger","star"],
    sabia:"Mateus conta a vida de Jesus, mostrando que Ele é o Salvador prometido, desde o seu nascimento em Belém até seus ensinamentos e milagres.",
    tema:"Jesus veio para cumprir as promessas de Deus e nos ensinar a amar.",
    activity:{ type:"quiz", question:"Onde Jesus nasceu?", options:["Belém","Roma","Egito"] },
    extra:{ icons:["manger","dove"], activity:{ type:"sequence", prompt:"Numere a vida de Jesus na ordem certa!",
      events:["Jesus nasce em Belém","Jesus cresce e começa a ensinar","Jesus faz milagres e cura pessoas","Jesus ensina sobre o amor de Deus"] } } },

  { n:41, id:"marcos", test:"NT", section:"evangelhos", name:"Marcos",
    icons:["boat","fish"],
    sabia:"Marcos é o evangelho mais rápido de todos, cheio de histórias sobre os milagres que Jesus fez, como acalmar tempestades e curar doentes.",
    tema:"Jesus tem poder para cuidar de nós em qualquer situação.",
    activity:{ type:"count", icon:"fish", color:"#4FC3F7", count:5, question:"Jesus multiplicou pães e peixes! Quantos peixinhos você encontra?" },
    extra:{ icons:["boat","water"], activity:{ type:"quiz", question:"O que Jesus fez quando a tempestade assustou os discípulos?", options:["Acalmou o vento e o mar","Foi embora nadando","Ficou com medo também"] } } },

  { n:42, id:"lucas", test:"NT", section:"evangelhos", name:"Lucas",
    icons:["heart","sheep"],
    sabia:"Lucas mostra o quanto Jesus amava e cuidava de todas as pessoas, principalmente quem precisava de ajuda, como na história da ovelha perdida.",
    tema:"Jesus ama e cuida de cada pessoa, sem deixar ninguém de fora.",
    activity:{ type:"maze", prompt:"Ajude o pastor a encontrar a ovelhinha perdida!", startIcon:"person", endIcon:"sheep" },
    extra:{ icons:["heart"], activity:{ type:"fill", sentence:"Jesus contou a história do bom samaritano para ensinar sobre ____.", wordBank:["cuidar do próximo","correr rápido","construir casas"] } } },

  { n:43, id:"joao", test:"NT", section:"evangelhos", name:"João",
    icons:["dove","heart"],
    sabia:"João mostra de um jeito muito especial o grande amor de Jesus pelas pessoas, dizendo que Ele veio para que todos tivessem vida.",
    tema:"Jesus ama muito cada um de nós.",
    activity:{ type:"fill", sentence:"Deus amou tanto o mundo que enviou o seu ____.", wordBank:["Filho","Anjo","Profeta"] },
    extra:{ icons:["heart"], activity:{ type:"count", icon:"heart", color:"#EF476F", count:6, question:"O amor de Jesus é enorme! Quantos coraçõezinhos você encontra?" } } },

  // ---------------- HISTÓRICO (NT) ----------------
  { n:44, id:"atos", test:"NT", section:"historicos_nt", name:"Atos",
    icons:["dove","road"],
    sabia:"Atos conta como os amigos de Jesus (os apóstolos) receberam a ajuda do Espírito Santo e contaram para muitas pessoas sobre o amor de Deus.",
    tema:"Podemos contar aos outros sobre o amor de Deus, com coragem.",
    activity:{ type:"wordsearch", words:["ATOS","APOSTOLOS","IGREJA","ESPIRITO"] },
    extra:{ icons:["road","dove"], activity:{ type:"sequence", prompt:"Numere os fatos na ordem certa!",
      events:["Jesus sobe ao céu","O Espírito Santo vem ajudar os discípulos","Os apóstolos contam sobre Jesus a muitas pessoas","A igreja cresce em vários lugares"] } } },

  // ---------------- CARTAS PAULINAS ----------------
  { n:45, id:"romanos", test:"NT", section:"cartas_paulinas", name:"Romanos",
    icons:["scroll","cross"],
    sabia:"Romanos é uma carta do apóstolo Paulo explicando como o amor e o perdão de Deus estão disponíveis para todas as pessoas.",
    tema:"Todos podem receber o amor e o perdão de Deus.",
    activity:{ type:"truefalse", statements:["O perdão de Deus é para todos.","Só pessoas perfeitas podem ser amadas por Deus."] } },

  { n:46, id:"1corintios", test:"NT", section:"cartas_paulinas", name:"1 Coríntios",
    icons:["heart","letter"],
    sabia:"1 Coríntios fala muito sobre o amor. Paulo escreveu que o amor é paciente, é bondoso e não guarda mágoa.",
    tema:"O verdadeiro amor é paciente e bondoso.",
    activity:{ type:"quiz", question:"Segundo 1 Coríntios, como é o amor de verdade?", options:["Paciente e bondoso","Impaciente e egoísta","Cheio de raiva"] } },

  { n:47, id:"2corintios", test:"NT", section:"cartas_paulinas", name:"2 Coríntios",
    icons:["letter","sun"],
    sabia:"2 Coríntios fala sobre como Deus nos conforta nas dificuldades e como é bom compartilhar com generosidade.",
    tema:"Deus nos conforta, e podemos ser generosos com os outros.",
    activity:{ type:"draw", prompt:"Desenhe algo que você poderia compartilhar com um amigo!" } },

  { n:48, id:"galatas", test:"NT", section:"cartas_paulinas", name:"Gálatas",
    icons:["vine","heart"],
    sabia:"Gálatas fala sobre o 'fruto do Espírito': amor, alegria, paz, paciência e bondade, que crescem em quem confia em Deus.",
    tema:"Deus nos ajuda a crescer com amor, alegria e paz no coração.",
    activity:{ type:"wordsearch", prompt:"Encontre os frutos do Espírito escondidos!", words:["AMOR","ALEGRIA","PAZ","BONDADE"] } },

  { n:49, id:"efesios", test:"NT", section:"cartas_paulinas", name:"Efésios",
    icons:["shield","cross"],
    sabia:"Efésios fala sobre a 'armadura de Deus': ferramentas especiais, como a verdade e a fé, que nos ajudam a fazer o bem todos os dias.",
    tema:"Deus nos dá força para escolher o caminho certo.",
    activity:{ type:"match", left:["Verdade","Fé","Amor"], right:["Ajuda a não mentir","Ajuda a confiar em Deus","Ajuda a cuidar dos outros"] } },

  { n:50, id:"filipenses", test:"NT", section:"cartas_paulinas", name:"Filipenses",
    icons:["star","heart"],
    sabia:"Filipenses é conhecida como a carta da alegria! Paulo escreveu que podemos estar alegres confiando em Deus, mesmo em momentos difíceis.",
    tema:"A alegria de Deus pode estar em nosso coração todos os dias.",
    activity:{ type:"draw", prompt:"Desenhe algo que te deixa muito alegre!" } },

  { n:51, id:"colossenses", test:"NT", section:"cartas_paulinas", name:"Colossenses",
    icons:["cross","heart"],
    sabia:"Colossenses ensina que Jesus é muito importante, e que devemos vestir nosso coração de amor, bondade e paciência.",
    tema:"Podemos 'vestir' o nosso coração com amor todos os dias.",
    activity:{ type:"fill", sentence:"Devemos vestir nosso coração de ____.", wordBank:["amor e bondade","raiva","tristeza"] } },

  { n:52, id:"1tessalonicenses", test:"NT", section:"cartas_paulinas", name:"1 Tessalonicenses",
    icons:["star","cloud"],
    sabia:"1 Tessalonicenses fala sobre viver com amor uns pelos outros e sobre a esperança de que Jesus vai voltar um dia.",
    tema:"Podemos viver com esperança e amor todos os dias.",
    activity:{ type:"truefalse", statements:["A carta fala sobre esperança e amor.","A carta fala sobre ficar triste sempre."] } },

  { n:53, id:"2tessalonicenses", test:"NT", section:"cartas_paulinas", name:"2 Tessalonicenses",
    icons:["sun","scroll"],
    sabia:"2 Tessalonicenses incentiva o povo a continuar fazendo o bem e trabalhando com alegria, enquanto espera por Jesus.",
    tema:"Podemos continuar fazendo o bem, mesmo enquanto esperamos.",
    activity:{ type:"quiz", question:"O que a carta pede para o povo continuar fazendo?", options:["O bem, com alegria","Nada, só esperar parado","Reclamar"] } },

  { n:54, id:"1timoteo", test:"NT", section:"cartas_paulinas", name:"1 Timóteo",
    icons:["book","heart"],
    sabia:"1 Timóteo é uma carta que Paulo escreveu para Timóteo, um jovem líder, ensinando como cuidar bem da igreja e ser um bom exemplo.",
    tema:"Podemos ser um bom exemplo, mesmo sendo jovens.",
    activity:{ type:"draw", prompt:"Desenhe você sendo um bom exemplo para alguém!" } },

  { n:55, id:"2timoteo", test:"NT", section:"cartas_paulinas", name:"2 Timóteo",
    icons:["scroll","star"],
    sabia:"2 Timóteo foi uma das últimas cartas de Paulo, incentivando Timóteo a continuar firme e corajoso na fé.",
    tema:"Podemos ser firmes e corajosos, confiando em Deus até o fim.",
    activity:{ type:"fill", sentence:"A Bíblia é útil para nos ____.", wordBank:["ensinar","confundir","assustar"] } },

  { n:56, id:"tito", test:"NT", section:"cartas_paulinas", name:"Tito",
    icons:["book","heart"],
    sabia:"Tito é uma carta parecida com a de Timóteo, incentivando a fazer o bem e cuidar bem da igreja com sabedoria.",
    tema:"Fazer o bem é sempre uma boa escolha.",
    activity:{ type:"truefalse", statements:["Fazer o bem agrada a Deus.","Não importa como tratamos os outros."] } },

  { n:57, id:"filemom", test:"NT", section:"cartas_paulinas", name:"Filemom",
    icons:["letter","heart"],
    sabia:"Filemom é uma cartinha bem curta que Paulo escreveu pedindo que um amigo perdoasse e recebesse de volta alguém com amor, como um irmão.",
    tema:"O perdão pode transformar uma amizade.",
    activity:{ type:"quiz", question:"O que Paulo pediu a Filemom?", options:["Que perdoasse e recebesse com amor","Que ficasse bravo para sempre","Que ignorasse a pessoa"] } },

  // ---------------- CARTAS GERAIS ----------------
  { n:58, id:"hebreus", test:"NT", section:"cartas_gerais", name:"Hebreus",
    icons:["cross","crown"],
    sabia:"Hebreus mostra o quanto Jesus é especial, e conta sobre pessoas da Bíblia que tiveram muita fé, mesmo sem ver tudo acontecer.",
    tema:"A fé nos ajuda a confiar em Deus mesmo sem ver tudo.",
    activity:{ type:"wordsearch", words:["FE","JESUS","CONFIANCA"] } },

  { n:59, id:"tiago", test:"NT", section:"cartas_gerais", name:"Tiago",
    icons:["heart","book"],
    sabia:"Tiago ensina que a nossa fé deve aparecer nas nossas atitudes, como ajudar quem precisa e falar com bondade.",
    tema:"Fé de verdade se mostra em atitudes boas.",
    activity:{ type:"quiz", question:"Como podemos mostrar nossa fé?", options:["Ajudando quem precisa","Só falando, sem fazer nada","Ignorando os outros"] } },

  { n:60, id:"1pedro", test:"NT", section:"cartas_gerais", name:"1 Pedro",
    icons:["shield","star"],
    sabia:"1 Pedro incentiva o povo a ter esperança e coragem, mesmo quando as coisas estão difíceis, porque Deus cuida de todos.",
    tema:"Podemos ter esperança mesmo nos dias difíceis.",
    activity:{ type:"truefalse", statements:["Deus cuida de nós nos dias difíceis.","Devemos desistir quando é difícil."] } },

  { n:61, id:"2pedro", test:"NT", section:"cartas_gerais", name:"2 Pedro",
    icons:["star","scroll"],
    sabia:"2 Pedro incentiva as pessoas a crescerem cada dia mais no conhecimento de Deus e a confiarem nas suas promessas.",
    tema:"Podemos crescer um pouquinho mais a cada dia no amor de Deus.",
    activity:{ type:"draw", prompt:"Desenhe uma plantinha crescendo — assim é a nossa fé, crescendo aos poucos!" } },

  { n:62, id:"1joao", test:"NT", section:"cartas_gerais", name:"1 João",
    icons:["heart","dove"],
    sabia:"1 João repete várias vezes uma frase linda: 'Deus é amor'. A carta ensina que devemos amar uns aos outros como Deus nos ama.",
    tema:"Deus é amor, e podemos amar uns aos outros.",
    activity:{ type:"fill", sentence:"Deus é ____.", wordBank:["amor","distante","bravo"] } },

  { n:63, id:"2joao", test:"NT", section:"cartas_gerais", name:"2 João",
    icons:["letter","heart"],
    sabia:"2 João é uma cartinha curta que pede para vivermos na verdade e no amor uns pelos outros.",
    tema:"Verdade e amor devem andar sempre juntos.",
    activity:{ type:"truefalse", statements:["Devemos viver com verdade e amor.","Mentir é uma boa ideia."] } },

  { n:64, id:"3joao", test:"NT", section:"cartas_gerais", name:"3 João",
    icons:["letter","heart"],
    sabia:"3 João é outra cartinha curta, que elogia quem recebe bem os outros e ajuda quem faz o bem.",
    tema:"Receber bem as pessoas é um jeito de mostrar amor.",
    activity:{ type:"quiz", question:"O que 3 João valoriza?", options:["Receber bem as pessoas","Ser mal-educado","Não ajudar ninguém"] } },

  { n:65, id:"judas", test:"NT", section:"cartas_gerais", name:"Judas",
    icons:["shield","star"],
    sabia:"Judas é um livro bem curtinho que incentiva o povo a continuar firme na fé e no amor de Deus, mesmo com desafios ao redor.",
    tema:"Podemos ficar firmes no amor de Deus.",
    activity:{ type:"truefalse", statements:["Podemos ficar firmes no amor de Deus.","É bom desistir da fé fácil."] } },

  // ---------------- APOCALIPSE ----------------
  { n:66, id:"apocalipse", test:"NT", section:"apocalipse", name:"Apocalipse",
    icons:["rainbow","crown","star"],
    sabia:"Apocalipse é o último livro da Bíblia. Ele mostra uma linda promessa: um dia, Deus vai fazer um lugar novo, onde não existirá mais tristeza nem lágrimas, e todos poderão viver felizes para sempre com Ele.",
    tema:"Deus promete um final cheio de esperança e alegria para quem confia Nele.",
    activity:{ type:"draw", prompt:"Desenhe como você imagina esse lugar novo e feliz que Deus promete!" },
    extra:{ icons:["star","rainbow"], activity:{ type:"fill", sentence:"No final, Deus promete enxugar todas as ____.", wordBank:["lágrimas","estrelas","montanhas"] } } },
];

const BIG_BOOK_IDS = ["genesis","exodo","salmos","isaias","mateus","marcos","lucas","joao","atos"];

/* ---------------- CONTEÚDO EXTRA (fora dos 66 livros) ---------------- */

const INTRO_PAGES = [
  { kind:"cover" },
  { title:"Bem-vindo(a), explorador(a)!",
    icons:["book","star"],
    body:"Este livro é a sua chave para conhecer a Bíblia inteira, do primeiro ao último livro! Você vai viajar por 66 livros, conhecer personagens incríveis e fazer muitas atividades divertidas pelo caminho." },
  { title:"O que é a Bíblia?",
    icons:["book","heart"],
    body:"A Bíblia não é só um livro — é uma biblioteca com 66 livros! Ela conta a história do amor de Deus pelas pessoas, do começo do mundo até a linda promessa do futuro." },
  { title:"Duas grandes partes",
    icons:["scroll","cross"],
    body:"A Bíblia se divide em duas partes: o Antigo Testamento (39 livros, escritos antes de Jesus nascer) e o Novo Testamento (27 livros, que contam sobre Jesus e a igreja). 39 + 27 = 66 livros!" },
  { title:"Sua missão",
    icons:["road","star"],
    body:"A cada livro que você conhecer, marque no seu Passaporte Bíblico, lá no fim deste caderno. Quando completar os 66, você ganha o seu Certificado de Explorador(a) da Bíblia!" },
];

const HOWTO_PAGES = [
  { title:"Como usar este livro",
    icons:["book","star"],
    body:"Cada livro da Bíblia tem uma página (ou mais!) com: o nome do livro, um 'Você sabia?', o tema principal, um desenho e uma atividade. Vá no seu ritmo — não precisa fazer tudo de uma vez!" },
  { title:"Legenda das atividades",
    legend:true,
    body:"Fique de olho nestes símbolos — eles mostram o tipo de atividade de cada página." },
  { title:"Dica para os adultos",
    icons:["heart","book"],
    body:"Leia com a criança, converse sobre o 'Você sabia?' e deixe que ela mesma escolha por onde começar. Não existe ordem obrigatória — o importante é a jornada!" },
  { title:"Materiais que você vai precisar",
    icons:["book","star"],
    body:"Lápis de cor, lápis comum e muita imaginação! Algumas páginas pedem para desenhar, outras para circular ou escrever — tudo bem simples." },
];

const AT_SECTIONS_MAP = [
  { key:"pentateuco", books:"Gênesis, Êxodo, Levítico, Números, Deuteronômio",
    text:"O Pentateuco conta como tudo começou: a criação do mundo e as primeiras famílias que confiaram em Deus." },
  { key:"historicos_at", books:"Josué, Juízes, Rute, 1 e 2 Samuel, 1 e 2 Reis, 1 e 2 Crônicas, Esdras, Neemias, Ester",
    text:"Os livros históricos contam o que aconteceu com o povo de Deus: viagens, reis, batalhas e muitas aventuras reais." },
  { key:"poeticos", books:"Jó, Salmos, Provérbios, Eclesiastes, Cânticos",
    text:"Os livros poéticos mostram como o povo conversava com Deus: músicas, orações e conselhos sábios." },
  { key:"profeticos_maiores", books:"Isaías, Jeremias, Lamentações, Ezequiel, Daniel",
    text:"Os profetas maiores anunciavam mensagens importantes de Deus, cheias de avisos e esperança." },
  { key:"profeticos_menores", books:"Oseias, Joel, Amós, Obadias, Jonas, Miqueias, Naum, Habacuque, Sofonias, Ageu, Zacarias, Malaquias",
    text:"Os profetas menores são 12 livros mais curtinhos, mas cheios de mensagens sobre justiça, fé e esperança." },
];

const NT_SECTIONS_MAP = [
  { key:"evangelhos", books:"Mateus, Marcos, Lucas, João",
    text:"Os Evangelhos contam a vida de Jesus: seu nascimento, seus ensinamentos, milagres, morte e ressurreição." },
  { key:"historicos_nt", books:"Atos",
    text:"Atos conta como a igreja começou e cresceu, depois que Jesus subiu ao céu." },
  { key:"cartas_paulinas", books:"Romanos, 1 e 2 Coríntios, Gálatas, Efésios, Filipenses, Colossenses, 1 e 2 Tessalonicenses, 1 e 2 Timóteo, Tito, Filemom",
    text:"Cartas escritas pelo apóstolo Paulo, cheias de ensinamentos para viver com amor e fé." },
  { key:"cartas_gerais", books:"Hebreus, Tiago, 1 e 2 Pedro, 1, 2 e 3 João, Judas",
    text:"Cartas escritas por outros apóstolos, incentivando o povo a viver com fé, amor e esperança." },
  { key:"apocalipse", books:"Apocalipse",
    text:"O último livro da Bíblia, cheio de esperança: Deus promete um futuro novo e feliz para sempre." },
];

const EXTRA_GAMES = [
  { title:"Trilha da Criação", icons:["sun","tree"],
    activity:{ type:"maze", prompt:"Ajude a formiguinha a atravessar o jardim que Deus criou!", startIcon:"seed", endIcon:"sun" } },
  { title:"Caça-palavras: Antigo Testamento", icons:["scroll","star"],
    activity:{ type:"wordsearch", words:["MOISES","DAVI","NOE","JOSUE"] } },
  { title:"Caça-palavras: Novo Testamento", icons:["cross","dove"],
    activity:{ type:"wordsearch", words:["JESUS","PEDRO","PAULO","MARIA"] } },
  { title:"Ligue os pares famosos", icons:["ark","bigFish"],
    activity:{ type:"match", prompt:"Ligue cada personagem à sua dupla famosa!",
      left:["Noé","Jonas","Davi","Daniel"], right:["Arca","Grande peixe","Golias","Leões"] } },
  { title:"Verdadeiro ou falso: heróis da fé", icons:["shield","crown"],
    activity:{ type:"truefalse", statements:["Davi enfrentou Golias com uma pedra e um estilingue.","Jonas passeou tranquilo dentro do peixe.","Daniel confiava em Deus mesmo com medo."] } },
  { title:"Labirinto até a Terra Prometida", icons:["road","star"],
    activity:{ type:"maze", prompt:"Ajude o povo de Israel a atravessar o deserto!", startIcon:"tent", endIcon:"star" } },
  { title:"Quantos animais entraram na arca?", icons:["ark","sheep"],
    activity:{ type:"count", icon:"sheep", color:"#F7F5EB", count:8, question:"Encontre os animais que embarcaram na arca de Noé!" } },
  { title:"Complete: frutos do Espírito", icons:["vine","heart"],
    activity:{ type:"fill", sentence:"Amor, alegria, paz e ____ são frutos do Espírito.", wordBank:["paciência","pressa","preguiça"] } },
  { title:"Numere a Semana Santa", icons:["cross","tomb"],
    activity:{ type:"sequence", prompt:"Numere os fatos na ordem certa!",
      events:["Jesus entra em Jerusalém","Jesus janta com os discípulos","Jesus morre na cruz","Jesus ressuscita ao terceiro dia"] } },
  { title:"Desenhe seu herói bíblico favorito", icons:["star","heart"],
    activity:{ type:"draw", prompt:"Qual personagem da Bíblia você mais gosta? Desenhe-o aqui!" } },
  { title:"Circule o caminho da sabedoria", icons:["balance","scroll"],
    activity:{ type:"quiz", question:"O que Salomão pediu a Deus para governar bem?", options:["Sabedoria","Riquezas","Fama"] } },
  { title:"Caça-palavras: lugares da Bíblia", icons:["cityWall","tent"],
    activity:{ type:"wordsearch", words:["EGITO","JERICO","BELEM","EDEN"] } },
  { title:"Ligue o profeta ao seu símbolo", icons:["lion","bigFish"],
    activity:{ type:"match", left:["Daniel","Jonas","Elias"], right:["Leões","Grande peixe","Redemoinho de fogo"] } },
  { title:"Desafio da amizade", icons:["heart","sheep"],
    activity:{ type:"challenge", prompt:"Pense e responda:", text:"Como Rute mostrou amizade e bondade com Noemi? Escreva ou desenhe sua resposta." } },
  { title:"Labirinto da esperança", icons:["rainbow","star"],
    activity:{ type:"maze", prompt:"Siga o caminho até o arco-íris da promessa de Deus!", startIcon:"cloud", endIcon:"rainbow" } },
];

const COLORING_PAGES = [
  { title:"A Criação",        icons:["sun","tree"] },
  { title:"A Arca de Noé",     icons:["ark"] },
  { title:"Moisés e o Mar",    icons:["water","person"] },
  { title:"Davi e Golias",     icons:["shield","crown"] },
  { title:"Jonas e o Peixe",   icons:["bigFish"] },
  { title:"Daniel e os Leões", icons:["lion"] },
  { title:"O Nascimento de Jesus", icons:["manger","star"] },
  { title:"Jesus e as Ovelhinhas", icons:["sheep","person"] },
  { title:"A Última Ceia",     icons:["book","cross"] },
  { title:"A Ressurreição",    icons:["tomb","sun"] },
  { title:"Pentecostes",       icons:["dove"] },
  { title:"O Arco-íris da Promessa", icons:["rainbow"] },
  { title:"Louvor com Harpa",  icons:["harp","music"] },
  { title:"Coroa de Rei",      icons:["crown"] },
  { title:"Um Novo Céu e uma Nova Terra", icons:["star","rainbow"] },
];

const CHALLENGE_PAGES = [
  { n:5,  text:"Você completou 5 livros!",  sub:"Continue explorando a Bíblia!" },
  { n:10, text:"Você completou 10 livros!", sub:"Muito bem, explorador(a)!" },
  { n:20, text:"Você completou 20 livros!", sub:"Sua jornada está incrível!" },
  { n:33, text:"Você chegou à metade da jornada!", sub:"33 livros conhecidos!" },
  { n:39, text:"Você completou o Antigo Testamento!", sub:"39 livros marcados no passaporte!" },
  { n:40, text:"Você chegou ao Novo Testamento!", sub:"Falta pouco para o final!" },
  { n:50, text:"Você completou 50 livros!", sub:"Uau, quase lá!" },
  { n:60, text:"Você completou 60 livros!", sub:"A reta final começou!" },
  { n:66, text:"Você completou os 66 livros!", sub:"Você conhece a Bíblia inteira! Parabéns!" },
];
